### ISSUE TITLE
Functionality testing on real card 

### ISSUE THREAD

**Issue by Urvek** [JavaCardSpot-dev/cryptsetup-javacard#8]
Test various functions provided by cryptsetup-javacard on real card after code improvement.
following tasks need to perform
1. Install cryptsetup-javacard on SmartCafe Expert 6.0 80K Dual card.
2. Export public-key from applet
3. Change Master Password
4. create new LUKS partition
5. Open/Unlock LUKS partition 
6. Delete partitionkey from the card
7. Erase the recovery passphrase data from the partition header

**Comment by Urvek** [comment]
The cryptsetup-javacard applet has been successfully installed on SmartCafe Expert 6.0 80K Dual card and tested limited functionality of applet.

**Comment by hiteshlilhare** [comment]
As discussed in the class with @petrs regarding not able to communicate with Javacard by using the client classes provided by the developers of cryptsetup-javacard. we tried connecting by putting some code from GlobalPlatformPro which definitely helped in connecting with card but we have to modify the code many places because the client code is tightly coupled with the connecting methodology with javacard. Therefore, we were able test limited functionality.
